export const products = [
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76901",
    slug: "wood-tool",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: {
          firstName: "Margot",
          lastName: "Batz",
        },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Wood Tool",
    price: 250,
    size: null,
    discount: 15,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-1.png",
    images: [
      "/assets/images/furniture-products/furniture-1.png",
      "/assets/images/furniture-products/furniture-1.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "new-arrival" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76902",
    slug: "brown-single",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: {
          firstName: "Margot",
          lastName: "Batz",
        },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Brown Single",
    price: 150,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-2.png",
    images: [
      "/assets/images/furniture-products/furniture-2.png",
      "/assets/images/furniture-products/furniture-2.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "new-arrival" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76903",
    slug: "hanging-sofa",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: {
          firstName: "Margot",
          lastName: "Batz",
        },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Hanging Sofa",
    price: 110,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-3.png",
    images: [
      "/assets/images/furniture-products/furniture-3.png",
      "/assets/images/furniture-products/furniture-3.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "new-arrival" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76904",
    slug: "round-sofa",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: {
          firstName: "Margot",
          lastName: "Batz",
        },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Round Sofa",
    price: 230,
    size: null,
    discount: 20,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-4.png",
    images: [
      "/assets/images/furniture-products/furniture-4.png",
      "/assets/images/furniture-products/furniture-4.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "new-arrival" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76905",
    slug: "single-round-sofa",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: {
          firstName: "Margot",
          lastName: "Batz",
        },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Single Round Sofa",
    price: 130,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-5.png",
    images: [
      "/assets/images/furniture-products/furniture-5.png",
      "/assets/images/furniture-products/furniture-5.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "new-arrival" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76906",
    slug: "accent-chair",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: {
          firstName: "Margot",
          lastName: "Batz",
        },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Accent Chair",
    price: 230,
    size: null,
    discount: 12,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-6.png",
    images: [
      "/assets/images/furniture-products/furniture-6.png",
      "/assets/images/furniture-products/furniture-6.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "new-arrival" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76907",
    slug: "brown-arm-chair",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: {
          firstName: "Margot",
          lastName: "Batz",
        },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Brown Arm Chair",
    price: 210,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-7.png",
    images: [
      "/assets/images/furniture-products/furniture-7.png",
      "/assets/images/furniture-products/furniture-7.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "new-arrival" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76908",
    slug: "brown-table",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Brown Table",
    price: 210,
    size: null,
    discount: 10,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-8.png",
    images: [
      "/assets/images/furniture-products/furniture-8.png",
      "/assets/images/furniture-products/furniture-8.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "new-arrival" },
  },

  // TRENDING PRODUCTS
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76909",
    slug: "double-seat-sofa",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Double Seat Sofa",
    price: 230,
    size: null,
    discount: 10,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-20.png",
    images: [
      "/assets/images/furniture-products/furniture-20.png",
      "/assets/images/furniture-products/furniture-20.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "trending" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76910",
    slug: "wood-tool-2",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Wood Tool 2",
    price: 250,
    size: null,
    discount: 15,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-1.png",
    images: [
      "/assets/images/furniture-products/furniture-1.png",
      "/assets/images/furniture-products/furniture-1.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "trending" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76911",
    slug: "navy-blue-sofa",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Navy Blue Sofa",
    price: 260,
    size: null,
    discount: 15,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-19.png",
    images: [
      "/assets/images/furniture-products/furniture-19.png",
      "/assets/images/furniture-products/furniture-19.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "trending" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76912",
    slug: "round-sofa-2",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Round Sofa 2",
    price: 230,
    size: null,
    discount: 20,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-4.png",
    images: [
      "/assets/images/furniture-products/furniture-4.png",
      "/assets/images/furniture-products/furniture-4.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "trending" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b76913",
    slug: "accent-chair",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: {
          firstName: "Margot",
          lastName: "Batz",
        },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Accent Chair",
    price: 230,
    size: null,
    discount: 12,
    brand: null,
    thumbnail: "/assets/images/furniture-products/furniture-6.png",
    images: [
      "/assets/images/furniture-products/furniture-6.png",
      "/assets/images/furniture-products/furniture-6.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "furniture-2", type: "trending" },
  },
];

export const testimonialList = [
  {
    rating: 5,
    id: "aa95e3fd-c170-431a-b9cd-abaac45a048f",
    comment: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.`,
    user: {
      name: "Jonathon Doe",
      avatar: "/assets/images/faces/10.jpg",
      designation: "Executive Officer, Amazon",
    },
  },
  {
    rating: 5,
    id: "72c79d90-abc7-467d-b7b2-e94905a9e18a",
    comment: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.`,
    user: {
      name: "Jonathon Doe",
      avatar: "/assets/images/faces/10.jpg",
      designation: "Executive Officer, Amazon",
    },
  },
  {
    rating: 5,
    id: "fc39e3b3-de7b-4ffa-aa64-63ca0c21c5c8",
    comment: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit at amet.`,
    user: {
      name: "Jonathon Doe",
      avatar: "/assets/images/faces/10.jpg",
      designation: "Executive Officer, Amazon",
    },
  },
];

export const serviceList = [
  {
    id: "5f9bd366-9583-4e6d-9b11-abe74b9c5d96",
    icon: "Truck",
    title: "Worldwide Delivery",
    description: "We offer competitive prices on",
  },
  {
    id: "121cffea-6972-41f8-8094-98dca22d17bb",
    icon: "CreditCardVerified",
    title: "Safe Payment",
    description: "We offer competitive prices on",
  },
  {
    id: "5b94f5d8-71ec-40a6-b5b8-401286deba24",
    icon: "Shield",
    title: "Shop With Confidence",
    description: "We offer competitive prices on",
  },
  {
    id: "8c4bb18f-d914-4269-9c7c-3c6728ba33e9",
    icon: "CustomerService",
    title: "24/7 Support",
    description: "We offer competitive prices on",
  },
];
