export const products = [
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b769m1",
    slug: "xanax-1mg-tablet",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Xanax 1mg Tablet",
    price: 250,
    size: null,
    discount: 15,
    brand: null,
    thumbnail: "/assets/images/medical/m-3.png",
    images: ["/assets/images/medical/m-3.png", "/assets/images/medical/m-3.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "featured" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m2",
    slug: "pharma-desjgn",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Pharma Desjgn",
    price: 150,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/medical/m-4.png",
    images: ["/assets/images/medical/m-4.png", "/assets/images/medical/m-4.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "featured" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m3",
    slug: "monas-400mg-capsule",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Monas 400mg Capsule",
    price: 150,
    size: null,
    discount: 10,
    brand: null,
    thumbnail: "/assets/images/medical/m-5.png",
    images: ["/assets/images/medical/m-5.png", "/assets/images/medical/m-5.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "featured" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m4",
    slug: "comet-500mg-tablet",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Comet 500mg Tablet",
    price: 150,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/medical/m-6.png",
    images: ["/assets/images/medical/m-6.png", "/assets/images/medical/m-6.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "featured" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m5",
    slug: "sergel-tablet",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Sergel Tablet",
    price: 180,
    size: null,
    discount: 5,
    brand: null,
    thumbnail: "/assets/images/medical/m-7.png",
    images: ["/assets/images/medical/m-7.png", "/assets/images/medical/m-7.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "featured" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m6",
    slug: "digital-thermometer",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Digital Thermometer",
    price: 130,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/medical/m-8.png",
    images: ["/assets/images/medical/m-8.png", "/assets/images/medical/m-8.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "featured" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m7",
    slug: "gun-thermometer",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Gun Thermometer",
    price: 230,
    size: null,
    discount: 12,
    brand: null,
    thumbnail: "/assets/images/medical/m-9.png",
    images: ["/assets/images/medical/m-9.png", "/assets/images/medical/m-9.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "featured" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m8",
    slug: "makrite-9500-n95",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Makrite 9500 N95",
    price: 150,
    size: null,
    discount: 4,
    brand: null,
    thumbnail: "/assets/images/medical/m-10.png",
    images: ["/assets/images/medical/m-10.png", "/assets/images/medical/m-10.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "featured" },
  },

  // BEST SELLER PRODUCTS
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m9",
    slug: "pharma-desjgn",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Pharma Desjgn",
    price: 150,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/medical/m-4.png",
    images: ["/assets/images/medical/m-4.png", "/assets/images/medical/m-4.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "best" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b769m10",
    slug: "xanax-1mg-tablet",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Xanax 1mg Tablet",
    price: 250,
    size: null,
    discount: 15,
    brand: null,
    thumbnail: "/assets/images/medical/m-3.png",
    images: ["/assets/images/medical/m-3.png", "/assets/images/medical/m-3.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "best" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m11",
    slug: "comet-500mg-tablet",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Comet 500mg Tablet",
    price: 150,
    size: null,
    discount: 0,
    brand: null,
    thumbnail: "/assets/images/medical/m-6.png",
    images: ["/assets/images/medical/m-6.png", "/assets/images/medical/m-6.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "best" },
  },
  {
    id: "8b9f5a78-0dbb-4dd3-a718-aa7342b7690m12",
    slug: "monas-400mg-capsule",
    shop: {
      id: "584323a3-059a-4990-8498-aa4fac9f22a7",
      slug: "constant-shoppers",
      user: {
        id: "08959f95-8448-42a1-b71b-9903504aad9b",
        email: "Elmo_Shields20@yahoo.com",
        phone: "(779) 888-4964",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/549.jpg",
        password: "n1yvwoxzoG7t_Lc",
        dateOfBirth: "1967-12-07T08:26:11.321Z",
        verified: true,
        name: { firstName: "Margot", lastName: "Batz" },
      },
      email: "Larry.Roberts13@yahoo.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Monas 400mg Capsule",
    price: 150,
    size: null,
    discount: 10,
    brand: null,
    thumbnail: "/assets/images/medical/m-5.png",
    images: ["/assets/images/medical/m-5.png", "/assets/images/medical/m-5.png"],
    categories: [],
    status: null,
    reviews: [],
    rating: 4,
    for: { demo: "medical", type: "best" },
  },
];

export const testimonialList = [
  {
    rating: 5,
    id: "aa95e3fd-c170-431a-b9cd-abaac45a04m1",
    title: "Good Customer Service",
    comment: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in
    gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit
    at amet.`,
    user: {
      name: "Jonathon Doe",
      avatar: "/assets/images/faces/10.jpg",
      designation: "Executive Officer, Amazon",
    },
  },
  {
    rating: 5,
    id: "aa95e3fd-c170-431a-b9cd-abaac45a04m2",
    title: "Good Customer Service",
    comment: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in
    gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit
    at amet.`,
    user: {
      name: "Jonathon Doe",
      avatar: "/assets/images/faces/10.jpg",
      designation: "Executive Officer, Amazon",
    },
  },
  {
    rating: 5,
    id: "aa95e3fd-c170-431a-b9cd-abaac45a04m3",
    title: "Good Customer Service",
    comment: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Auctor libero id et, in
    gravida. Sit diam duis mauris nulla cursus. Erat et lectus vel ut sollicitudin elit
    at amet.`,
    user: {
      name: "Jonathon Doe",
      avatar: "/assets/images/faces/10.jpg",
      designation: "Executive Officer, Amazon",
    },
  },
];

export const serviceList = [
  {
    id: "5f9bd366-9583-4e6d-9b11-abe74b9c5d96",
    icon: "Truck",
    title: "Worldwide Delivery",
    description: "We offer competitive prices on",
  },
  {
    id: "121cffea-6972-41f8-8094-98dca22d17bb",
    icon: "CreditCardVerified",
    title: "Safe Payment",
    description: "We offer competitive prices on",
  },
  {
    id: "5b94f5d8-71ec-40a6-b5b8-401286deba24",
    icon: "Shield",
    title: "Shop With Confidence",
    description: "We offer competitive prices on",
  },
  {
    id: "8c4bb18f-d914-4269-9c7c-3c6728ba33e9",
    icon: "CustomerService",
    title: "24/7 Support",
    description: "We offer competitive prices on",
  },
];

export const blogs = [
  {
    id: "f54ee5db-ff89-4d86-ade8-86d949db7bm1",
    title: "Xiaomi Posts Slowest Ever Revenue-Growth In Third Quarter",
    description:
      "Saepe praesentium saepe iste minus totam excepturi expedita. Illum deserunt suscipit rerum officiis consequatur dicta odio. Necessitatibus perferendis aspernatur eum. Saepe voluptatum beatae. Hic veritatis libero nisi excepturi omnis explicabo et.",
    thumbnail: "/assets/images/blogs/blog-4.png",
    shop: {
      id: "c2a4ed2d-6708-4c1e-aa36-eddfd0496ce7",
      slug: "constant-shoppers",
      user: {
        id: "5c47a8cb-c032-4e5d-81ff-fd082f8f7740",
        email: "Berniece0@hotmail.com",
        phone: "730-935-5160 x73867",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/561.jpg",
        password: "Yj2bbCH9JqNNv_K",
        dateOfBirth: "1993-08-19T08:41:32.306Z",
        verified: true,
        name: { firstName: "Alphonso", lastName: "Goodwin" },
      },
      email: "Darian90@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    user: {
      id: "468e1914-4e05-4da7-b84b-b099a4832ce2",
      email: "Beaulah_Hodkiewicz@hotmail.com",
      phone: "407.691.9583",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/558.jpg",
      password: "K1v19JSlmawcx2Y",
      dateOfBirth: "1945-03-08T22:29:18.813Z",
      verified: true,
      name: { firstName: "Eloy", lastName: "Breitenberg" },
    },
    createdAt: "2022-11-08T07:15:55.897Z",
    slug: "xiaomi-posts-slowest-ever-revenue-growth-in-third-quarter",
  },
  {
    id: "f54ee5db-ff89-4d86-ade8-86d949db7bm2",
    title: "WhatsApp Shared ‘Technical Jargon’ With Govt Agency, Didn’t",
    slug: "whatsApp-shared-technical-jargon-with-govt-agency-didn’t",
    description:
      "Saepe praesentium saepe iste minus totam excepturi expedita. Illum deserunt suscipit rerum officiis consequatur dicta odio. Necessitatibus perferendis aspernatur eum. Saepe voluptatum beatae. Hic veritatis libero nisi excepturi omnis explicabo et.",
    thumbnail: "/assets/images/blogs/blog-5.png",
    shop: {
      id: "c2a4ed2d-6708-4c1e-aa36-eddfd0496ce7",
      slug: "constant-shoppers",
      user: {
        id: "5c47a8cb-c032-4e5d-81ff-fd082f8f7740",
        email: "Berniece0@hotmail.com",
        phone: "730-935-5160 x73867",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/561.jpg",
        password: "Yj2bbCH9JqNNv_K",
        dateOfBirth: "1993-08-19T08:41:32.306Z",
        verified: true,
        name: { firstName: "Alphonso", lastName: "Goodwin" },
      },
      email: "Darian90@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    user: {
      id: "468e1914-4e05-4da7-b84b-b099a4832ce2",
      email: "Beaulah_Hodkiewicz@hotmail.com",
      phone: "407.691.9583",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/558.jpg",
      password: "K1v19JSlmawcx2Y",
      dateOfBirth: "1945-03-08T22:29:18.813Z",
      verified: true,
      name: { firstName: "Eloy", lastName: "Breitenberg" },
    },
    createdAt: "2022-11-08T07:15:55.897Z",
  },
];
