export const serviceList = [
  {
    id: "5f9bd366-9583-4e6d-9b11-abe74b9c5d96",
    icon: "Truck",
    title: "Worldwide Delivery",
    description: "We offer competitive prices on",
  },
  {
    id: "121cffea-6972-41f8-8094-98dca22d17bb",
    icon: "CreditCardVerified",
    title: "Safe Payment",
    description: "We offer competitive prices on",
  },
  {
    id: "5b94f5d8-71ec-40a6-b5b8-401286deba24",
    icon: "Shield",
    title: "Shop With Confidence",
    description: "We offer competitive prices on",
  },
  {
    id: "8c4bb18f-d914-4269-9c7c-3c6728ba33e9",
    icon: "CustomerService",
    title: "24/7 Support",
    description: "We offer competitive prices on",
  },
];

export const products = [
  {
    id: "8ac53dd8-6418-454f-bbb5-29f0b26ac5a5",
    slug: "apple-watch",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Apple Watch",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/apple-watch-5.png",
    images: [
      "/assets/images/products/apple-watch-5.png",
      "/assets/images/products/apple-watch-5.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "best-seller" },
  },
  {
    id: "8ac53dd8-6418-454f-bbb4-29f0b26ac5a4",
    slug: "yamaha-speaker",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Yamaha Speaker",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/speaker.png",
    images: ["/assets/images/products/speaker.png", "/assets/images/products/speaker.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "best-seller" },
  },
  {
    id: "8ac53dd8-6418-454f-bbb3-29f0b26ac5a3",
    slug: "motorola-headphone",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Motorola Headphone",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/headphone-2.png",
    images: ["/assets/images/products/headphone-2.png", "/assets/images/products/headphone-2.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "best-seller" },
  },
  {
    id: "8ac53dd8-6418-454f-bbb2-29f0b26ac5a2",
    slug: "apple-watch",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Apple Watch",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/air-bud.png",
    images: ["/assets/images/products/air-bud.png", "/assets/images/products/air-bud.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "best-seller" },
  },
  {
    id: "8ac53dd8-6418-454f-bbb1-29f0b26ac5a1",
    slug: "sony-airbud",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Sony Airbud",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/drone-3.png",
    images: ["/assets/images/products/drone-3.png", "/assets/images/products/drone-3.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "best-seller" },
  },
  {
    id: "8ac53dd8-6418-454f-bbb9-29f0b26ac5a9",
    slug: "playstation-gear",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Playstation Gear",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/gaming-gear-2.png",
    images: [
      "/assets/images/products/gaming-gear-2.png",
      "/assets/images/products/gaming-gear-2.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "best-seller" },
  },
  {
    id: "8ac53dd8-6418-454f-bbb8-29f0b26ac5a8",
    slug: "jbl-speaker",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "JBL Speaker",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 25,
    thumbnail: "/assets/images/products/speaker-2.png",
    images: ["/assets/images/products/speaker-2.png", "/assets/images/products/speaker-2.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "best-seller" },
  },
  {
    id: "8ac53dd8-6418-454f-bbb7-29f0b26ac5a7",
    slug: "beats-headphone",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Beats Headphone",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/beat-headphone-2.png",
    images: [
      "/assets/images/products/beat-headphone-2.png",
      "/assets/images/products/beat-headphone-2.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "best-seller" },
  },

  // NEW ARRIVAL PRODUCTS
  {
    id: "8ac53dd8-6418-454f-bbc1-29f0b26ac5c1",
    slug: "smart-bag",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Smart Bag",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/bag-2.png",
    images: ["/assets/images/products/bag-2.png", "/assets/images/products/bag-2.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "new-arrival" },
  },
  {
    id: "8ac53dd8-6418-454f-bbc1-29f0b26ac5c1",
    slug: "canon-lens",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Canon Lens",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/canon-lens.png",
    images: ["/assets/images/products/canon-lens.png", "/assets/images/products/canon-lens.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "new-arrival" },
  },
  {
    id: "8ac53dd8-6418-454f-bbc1-29f0b26ac5c1",
    slug: "tp-link-router",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "TP Link Router",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/router.png",
    images: ["/assets/images/products/router.png", "/assets/images/products/router.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "new-arrival" },
  },
  {
    id: "8ac53dd8-6418-454f-bbc1-29f0b26ac5c1",
    slug: "boom-headphone",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Boom Headphone",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/headphone-3.png",
    images: ["/assets/images/products/headphone-3.png", "/assets/images/products/headphone-3.png"],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "new-arrival" },
  },
  {
    id: "8ac53dd8-6418-454f-bbb7-29f0b26ac5a7",
    slug: "beats-headphone",
    shop: {
      id: "baa3a02b-42da-40c0-852b-3aa292b70704",
      slug: "anytime-buys",
      user: {
        id: "e0d8be78-c530-4f1a-a2df-d082ba2db274",
        email: "Daisy.McLaughlin80@yahoo.com",
        phone: "1-462-772-4274 x931",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/174.jpg",
        password: "nAGr0Rkf8CLP4Sv",
        dateOfBirth: "1958-06-07T17:14:57.585Z",
        verified: true,
        name: { firstName: "Llewellyn", lastName: "Schmitt" },
      },
      email: "Vida.Simonis@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    title: "Beats Headphone",
    brand: null,
    price: 110,
    size: null,
    colors: [],
    discount: 0,
    thumbnail: "/assets/images/products/beat-headphone-2.png",
    images: [
      "/assets/images/products/beat-headphone-2.png",
      "/assets/images/products/beat-headphone-2.png",
    ],
    categories: [],
    status: null,
    reviews: [],
    for: { demo: "gadget-2", type: "new-arrival" },
  },
];

export const blogs = [
  {
    id: "f54ee5db-ff89-4d86-ade8-86d949db7bg1",
    title: "GameStop Will Provide Up to $1 Billion in",
    description:
      "Saepe praesentium saepe iste minus totam excepturi expedita. Illum deserunt suscipit rerum officiis consequatur dicta odio. Necessitatibus perferendis aspernatur eum. Saepe voluptatum beatae. Hic veritatis libero nisi excepturi omnis explicabo et.",
    thumbnail: "/assets/images/blogs/post-1.jpg",
    shop: {
      id: "c2a4ed2d-6708-4c1e-aa36-eddfd0496ce7",
      slug: "constant-shoppers",
      user: {
        id: "5c47a8cb-c032-4e5d-81ff-fd082f8f7740",
        email: "Berniece0@hotmail.com",
        phone: "730-935-5160 x73867",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/561.jpg",
        password: "Yj2bbCH9JqNNv_K",
        dateOfBirth: "1993-08-19T08:41:32.306Z",
        verified: true,
        name: { firstName: "Alphonso", lastName: "Goodwin" },
      },
      email: "Darian90@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    user: {
      id: "468e1914-4e05-4da7-b84b-b099a4832ce2",
      email: "Beaulah_Hodkiewicz@hotmail.com",
      phone: "407.691.9583",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/558.jpg",
      password: "K1v19JSlmawcx2Y",
      dateOfBirth: "1945-03-08T22:29:18.813Z",
      verified: true,
      name: { firstName: "Eloy", lastName: "Breitenberg" },
    },
    createdAt: "2022-11-08T07:15:55.897Z",
    slug: "gameStop-will-provide-up-to-$1-billion-in",
  },
  {
    id: "f54ee5db-ff89-4d86-ade8-86d949db7bg2",
    title: "GameStop Will Provide Up to $1 Billion in",
    description:
      "Saepe praesentium saepe iste minus totam excepturi expedita. Illum deserunt suscipit rerum officiis consequatur dicta odio. Necessitatibus perferendis aspernatur eum. Saepe voluptatum beatae. Hic veritatis libero nisi excepturi omnis explicabo et.",
    thumbnail: "/assets/images/blogs/post-1.jpg",
    shop: {
      id: "c2a4ed2d-6708-4c1e-aa36-eddfd0496ce7",
      slug: "constant-shoppers",
      user: {
        id: "5c47a8cb-c032-4e5d-81ff-fd082f8f7740",
        email: "Berniece0@hotmail.com",
        phone: "730-935-5160 x73867",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/561.jpg",
        password: "Yj2bbCH9JqNNv_K",
        dateOfBirth: "1993-08-19T08:41:32.306Z",
        verified: true,
        name: { firstName: "Alphonso", lastName: "Goodwin" },
      },
      email: "Darian90@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    user: {
      id: "468e1914-4e05-4da7-b84b-b099a4832ce2",
      email: "Beaulah_Hodkiewicz@hotmail.com",
      phone: "407.691.9583",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/558.jpg",
      password: "K1v19JSlmawcx2Y",
      dateOfBirth: "1945-03-08T22:29:18.813Z",
      verified: true,
      name: { firstName: "Eloy", lastName: "Breitenberg" },
    },
    createdAt: "2022-11-08T07:15:55.897Z",
    slug: "gameStop-will-provide-up-to-$1-billion-in",
  },
  {
    id: "f54ee5db-ff89-4d86-ade8-86d949db7bg3",
    title: "GameStop Will Provide Up to $1 Billion in",
    description:
      "Saepe praesentium saepe iste minus totam excepturi expedita. Illum deserunt suscipit rerum officiis consequatur dicta odio. Necessitatibus perferendis aspernatur eum. Saepe voluptatum beatae. Hic veritatis libero nisi excepturi omnis explicabo et.",
    thumbnail: "/assets/images/blogs/post-1.jpg",
    shop: {
      id: "c2a4ed2d-6708-4c1e-aa36-eddfd0496ce7",
      slug: "constant-shoppers",
      user: {
        id: "5c47a8cb-c032-4e5d-81ff-fd082f8f7740",
        email: "Berniece0@hotmail.com",
        phone: "730-935-5160 x73867",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/561.jpg",
        password: "Yj2bbCH9JqNNv_K",
        dateOfBirth: "1993-08-19T08:41:32.306Z",
        verified: true,
        name: { firstName: "Alphonso", lastName: "Goodwin" },
      },
      email: "Darian90@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    user: {
      id: "468e1914-4e05-4da7-b84b-b099a4832ce2",
      email: "Beaulah_Hodkiewicz@hotmail.com",
      phone: "407.691.9583",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/558.jpg",
      password: "K1v19JSlmawcx2Y",
      dateOfBirth: "1945-03-08T22:29:18.813Z",
      verified: true,
      name: { firstName: "Eloy", lastName: "Breitenberg" },
    },
    createdAt: "2022-11-08T07:15:55.897Z",
    slug: "gameStop-will-provide-up-to-$1-billion-in",
  },
  {
    id: "f54ee5db-ff89-4d86-ade8-86d949db7bg4",
    title: "GameStop Will Provide Up to $1 Billion in",
    description:
      "Saepe praesentium saepe iste minus totam excepturi expedita. Illum deserunt suscipit rerum officiis consequatur dicta odio. Necessitatibus perferendis aspernatur eum. Saepe voluptatum beatae. Hic veritatis libero nisi excepturi omnis explicabo et.",
    thumbnail: "/assets/images/blogs/post-1.jpg",
    shop: {
      id: "c2a4ed2d-6708-4c1e-aa36-eddfd0496ce7",
      slug: "constant-shoppers",
      user: {
        id: "5c47a8cb-c032-4e5d-81ff-fd082f8f7740",
        email: "Berniece0@hotmail.com",
        phone: "730-935-5160 x73867",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/561.jpg",
        password: "Yj2bbCH9JqNNv_K",
        dateOfBirth: "1993-08-19T08:41:32.306Z",
        verified: true,
        name: { firstName: "Alphonso", lastName: "Goodwin" },
      },
      email: "Darian90@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: { facebook: null, youtube: null, twitter: null, instagram: null },
    },
    user: {
      id: "468e1914-4e05-4da7-b84b-b099a4832ce2",
      email: "Beaulah_Hodkiewicz@hotmail.com",
      phone: "407.691.9583",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/558.jpg",
      password: "K1v19JSlmawcx2Y",
      dateOfBirth: "1945-03-08T22:29:18.813Z",
      verified: true,
      name: { firstName: "Eloy", lastName: "Breitenberg" },
    },
    createdAt: "2022-11-08T07:15:55.897Z",
    slug: "gameStop-will-provide-up-to-$1-billion-in",
  },
];
